# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: grammar-up
'on':
  push:
    branches:
      - master
    tags:
      - '*'
concurrency:
  group: up-${{ github.ref }}
  cancel-in-progress: true
jobs:
  grammar-up:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: |-
          latest=$(curl --silent -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/objectionary/eo/releases/latest | jq -r '.tag_name')
          sed -E -i "s/VERSION := [0-9\.]+/VERSION := ${latest}/" Makefile
      - uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          branch: version-up
          commit-message: 'New EO grammar version in Makefile'
          delete-branch: true
          title: 'New EO grammar version in Makefile'
          assignees: yegor256
          base: master
